/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommandInfo: typeof import('./src/components/CommandInfo.vue')['default']
    CommandNode: typeof import('./src/components/FlowNodes/CommandNode.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    EndpointNode: typeof import('./src/components/FlowNodes/EndpointNode.vue')['default']
    EventNode: typeof import('./src/components/FlowNodes/EventNode.vue')['default']
    ExampleDisplay: typeof import('./src/components/ExampleDisplay.vue')['default']
    FlowBlock: typeof import('./src/components/FlowBlock.vue')['default']
    JsonSchemaDisplay: typeof import('./src/components/JsonSchemaDisplay.vue')['default']
    MarkdownContent: typeof import('./src/components/MarkdownContent.vue')['default']
    PayloadNode: typeof import('./src/components/FlowNodes/PayloadNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./src/components/ServiceCard.vue')['default']
    ServiceVersionInfo: typeof import('./src/components/ServiceVersionInfo.vue')['default']
    SubscriptionInfo: typeof import('./src/components/SubscriptionInfo.vue')['default']
    SubscriptionNode: typeof import('./src/components/FlowNodes/SubscriptionNode.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    TypeDisplay: typeof import('./src/components/TypeDisplay.vue')['default']
    YamlDisplay: typeof import('./src/components/YamlDisplay.vue')['default']
  }
}
